version: '3.9'
services:
  customer-service:
    image: customer_image
    container_name: customercontainer
    build: BEJ_C2_S3_REST_API_MONGODB_PC_1/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8087:8087
    depends_on:
      - mongoService
      - cloudapiservice


  mongoService:
    image: mongo
    container_name: mongoService
    ports:
      - 27017:27017
    networks:
      - mynetwork

  authentication-service:
    image: authentication_image
    container_name: authentication-service
    build: UserAuthentication/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8083:8083
    depends_on:
      - mysqlService
      - cloudapiservice


  mysqlService:
    image: mysql:latest
    container_name: mysqlservice
    networks:
      - mynetwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  cloudapiservice:
    image: apigateway-service
    build: SpringCloudAPIGateway
    restart: always
    networks:
      - mynetwork
    ports:
      - 9005:9005
  eureka-service:
    container_name: containerEureka
    build: EurekaServer/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8761:8761
networks:
  mynetwork:
    driver: bridge